spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/world
    username: root
    password: dinar5440@bk.ru
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

